// Auto-generated by: pnpm db:types
// Do not edit manually. Run `pnpm db:types` after schema changes.

export type Database = {
  public: {
    Tables: Record<string, never>;
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
  };
};
