// Auto-generated by: pnpm db:types
// Do not edit manually. Run `pnpm db:types` after schema changes.

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[]

export type Database = {
  public: {
    Tables: {
      business_profiles: {
        Row: {
          id: string
          user_id: string
          website_url: string
          company_name: string | null
          description: string | null
          industry: string | null
          product_summary: string | null
          value_proposition: string | null
          target_market: string | null
          raw_scraped_content: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          website_url: string
          company_name?: string | null
          description?: string | null
          industry?: string | null
          product_summary?: string | null
          value_proposition?: string | null
          target_market?: string | null
          raw_scraped_content?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          website_url?: string
          company_name?: string | null
          description?: string | null
          industry?: string | null
          product_summary?: string | null
          value_proposition?: string | null
          target_market?: string | null
          raw_scraped_content?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      icp_profiles: {
        Row: {
          id: string
          user_id: string
          business_profile_id: string | null
          job_titles: string[] | null
          seniority_levels: string[] | null
          industries: string[] | null
          company_sizes: string[] | null
          regions: string[] | null
          tech_stack: string[] | null
          revenue_ranges: string[] | null
          funding_stages: string[] | null
          keywords: string[] | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          business_profile_id?: string | null
          job_titles?: string[] | null
          seniority_levels?: string[] | null
          industries?: string[] | null
          company_sizes?: string[] | null
          regions?: string[] | null
          tech_stack?: string[] | null
          revenue_ranges?: string[] | null
          funding_stages?: string[] | null
          keywords?: string[] | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          business_profile_id?: string | null
          job_titles?: string[] | null
          seniority_levels?: string[] | null
          industries?: string[] | null
          company_sizes?: string[] | null
          regions?: string[] | null
          tech_stack?: string[] | null
          revenue_ranges?: string[] | null
          funding_stages?: string[] | null
          keywords?: string[] | null
          created_at?: string
          updated_at?: string
        }
      }
      search_campaigns: {
        Row: {
          id: string
          user_id: string
          icp_profile_id: string | null
          status: 'pending' | 'running' | 'completed' | 'failed'
          leads_found: number
          leads_scored: number
          started_at: string | null
          completed_at: string | null
          error_message: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          icp_profile_id?: string | null
          status?: 'pending' | 'running' | 'completed' | 'failed'
          leads_found?: number
          leads_scored?: number
          started_at?: string | null
          completed_at?: string | null
          error_message?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          icp_profile_id?: string | null
          status?: 'pending' | 'running' | 'completed' | 'failed'
          leads_found?: number
          leads_scored?: number
          started_at?: string | null
          completed_at?: string | null
          error_message?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      leads: {
        Row: {
          id: string
          user_id: string
          campaign_id: string | null
          first_name: string | null
          last_name: string | null
          full_name: string | null
          email: string | null
          linkedin_url: string | null
          photo_url: string | null
          job_title: string | null
          seniority: string | null
          company_name: string | null
          company_domain: string | null
          company_website: string | null
          industry: string | null
          company_size: string | null
          revenue_range: string | null
          funding_stage: string | null
          location: string | null
          country: string | null
          source: 'apollo' | 'google_places' | 'enriched' | null
          apollo_id: string | null
          raw_data: Json | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          campaign_id?: string | null
          first_name?: string | null
          last_name?: string | null
          full_name?: string | null
          email?: string | null
          linkedin_url?: string | null
          photo_url?: string | null
          job_title?: string | null
          seniority?: string | null
          company_name?: string | null
          company_domain?: string | null
          company_website?: string | null
          industry?: string | null
          company_size?: string | null
          revenue_range?: string | null
          funding_stage?: string | null
          location?: string | null
          country?: string | null
          source?: 'apollo' | 'google_places' | 'enriched' | null
          apollo_id?: string | null
          raw_data?: Json | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          campaign_id?: string | null
          first_name?: string | null
          last_name?: string | null
          full_name?: string | null
          email?: string | null
          linkedin_url?: string | null
          photo_url?: string | null
          job_title?: string | null
          seniority?: string | null
          company_name?: string | null
          company_domain?: string | null
          company_website?: string | null
          industry?: string | null
          company_size?: string | null
          revenue_range?: string | null
          funding_stage?: string | null
          location?: string | null
          country?: string | null
          source?: 'apollo' | 'google_places' | 'enriched' | null
          apollo_id?: string | null
          raw_data?: Json | null
          created_at?: string
          updated_at?: string
        }
      }
      lead_scores: {
        Row: {
          id: string
          user_id: string
          lead_id: string
          campaign_id: string | null
          total_score: number
          company_fit_score: number
          contact_fit_score: number
          buying_signals_score: number
          timing_score: number
          grade: 'HOT' | 'QUALIFIED' | 'ENGAGED' | 'POTENTIAL' | 'POOR'
          ai_reasoning: string | null
          recommended_action: string | null
          confidence: number | null
          dach_notes: string | null
          key_insights: string[] | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          lead_id: string
          campaign_id?: string | null
          total_score?: number
          company_fit_score?: number
          contact_fit_score?: number
          buying_signals_score?: number
          timing_score?: number
          grade?: 'HOT' | 'QUALIFIED' | 'ENGAGED' | 'POTENTIAL' | 'POOR'
          ai_reasoning?: string | null
          recommended_action?: string | null
          confidence?: number | null
          dach_notes?: string | null
          key_insights?: string[] | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          lead_id?: string
          campaign_id?: string | null
          total_score?: number
          company_fit_score?: number
          contact_fit_score?: number
          buying_signals_score?: number
          timing_score?: number
          grade?: 'HOT' | 'QUALIFIED' | 'ENGAGED' | 'POTENTIAL' | 'POOR'
          ai_reasoning?: string | null
          recommended_action?: string | null
          confidence?: number | null
          dach_notes?: string | null
          key_insights?: string[] | null
          created_at?: string
          updated_at?: string
        }
      }
      agent_logs: {
        Row: {
          id: string
          user_id: string
          campaign_id: string | null
          action_type:
            | 'campaign_started'
            | 'campaign_completed'
            | 'campaign_failed'
            | 'leads_discovered'
            | 'lead_scored'
            | 'query_optimized'
            | 'website_scraped'
            | 'website_analyzed'
            | 'lead_exported'
            | 'onboarding_started'
            | 'onboarding_completed'
            | 'research_started'
            | 'research_completed'
            | 'outreach_generated'
            | 'conversation_created'
          message: string
          metadata: Json | null
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          campaign_id?: string | null
          action_type:
            | 'campaign_started'
            | 'campaign_completed'
            | 'campaign_failed'
            | 'leads_discovered'
            | 'lead_scored'
            | 'query_optimized'
            | 'website_scraped'
            | 'website_analyzed'
            | 'lead_exported'
            | 'onboarding_started'
            | 'onboarding_completed'
            | 'research_started'
            | 'research_completed'
            | 'outreach_generated'
            | 'conversation_created'
          message: string
          metadata?: Json | null
          created_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          campaign_id?: string | null
          action_type?:
            | 'campaign_started'
            | 'campaign_completed'
            | 'campaign_failed'
            | 'leads_discovered'
            | 'lead_scored'
            | 'query_optimized'
            | 'website_scraped'
            | 'website_analyzed'
            | 'lead_exported'
            | 'onboarding_started'
            | 'onboarding_completed'
            | 'research_started'
            | 'research_completed'
            | 'outreach_generated'
            | 'conversation_created'
          message?: string
          metadata?: Json | null
          created_at?: string
        }
      }
      agent_conversations: {
        Row: {
          id: string
          user_id: string
          title: string | null
          model: string | null
          metadata: Json | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          title?: string | null
          model?: string | null
          metadata?: Json | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          title?: string | null
          model?: string | null
          metadata?: Json | null
          created_at?: string
          updated_at?: string
        }
      }
      agent_messages: {
        Row: {
          id: string
          conversation_id: string
          user_id: string
          role: 'user' | 'assistant' | 'system' | 'tool'
          content: string
          parts: Json | null
          tool_invocations: Json | null
          created_at: string
        }
        Insert: {
          id?: string
          conversation_id: string
          user_id: string
          role: 'user' | 'assistant' | 'system' | 'tool'
          content: string
          parts?: Json | null
          tool_invocations?: Json | null
          created_at?: string
        }
        Update: {
          id?: string
          conversation_id?: string
          user_id?: string
          role?: 'user' | 'assistant' | 'system' | 'tool'
          content?: string
          parts?: Json | null
          tool_invocations?: Json | null
          created_at?: string
        }
      }
      lead_research: {
        Row: {
          id: string
          user_id: string
          lead_id: string
          tech_stack: string[] | null
          hiring_info: string | null
          pricing_model: string | null
          news_summary: string | null
          impressum: Json | null
          handelsregister: string | null
          locations: string[] | null
          full_report: string
          sources: Json
          status: 'in_progress' | 'completed' | 'failed'
          error_message: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          lead_id: string
          tech_stack?: string[] | null
          hiring_info?: string | null
          pricing_model?: string | null
          news_summary?: string | null
          impressum?: Json | null
          handelsregister?: string | null
          locations?: string[] | null
          full_report: string
          sources?: Json
          status?: 'in_progress' | 'completed' | 'failed'
          error_message?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          lead_id?: string
          tech_stack?: string[] | null
          hiring_info?: string | null
          pricing_model?: string | null
          news_summary?: string | null
          impressum?: Json | null
          handelsregister?: string | null
          locations?: string[] | null
          full_report?: string
          sources?: Json
          status?: 'in_progress' | 'completed' | 'failed'
          error_message?: string | null
          created_at?: string
          updated_at?: string
        }
      }
    }
    Views: Record<string, never>
    Functions: Record<string, never>
    Enums: Record<string, never>
  }
}

// Convenience row types
export type BusinessProfile = Database['public']['Tables']['business_profiles']['Row']
export type IcpProfile = Database['public']['Tables']['icp_profiles']['Row']
export type SearchCampaign = Database['public']['Tables']['search_campaigns']['Row']
export type Lead = Database['public']['Tables']['leads']['Row']
export type LeadScore = Database['public']['Tables']['lead_scores']['Row']
export type AgentLog = Database['public']['Tables']['agent_logs']['Row']
export type AgentConversation = Database['public']['Tables']['agent_conversations']['Row']
export type AgentMessage = Database['public']['Tables']['agent_messages']['Row']
export type LeadResearch = Database['public']['Tables']['lead_research']['Row']
